"use strict"
// Tests for the shell constants of signing in (lib/Sh.js): PREPARE_DATA,
// SIGNIN_DIRS and COOKIE_EXPORT. They are run for real with /usr/bin/sh,
// under umask 022, inside a directory this file creates below the system's
// temporary directory and removes again. Nothing outside it is written.
//
// No browser and no real yt-dlp is involved, and no real profile is read:
// the export is given a stand-in for yt-dlp that this file writes, which
// records how it was started and writes a cookie file made of the invented
// rows below. One test ends a child, through the handle it spawned it with.
var test = require("node:test")
var assert = require("node:assert")
var childProcess = require("node:child_process")
var fs = require("node:fs")
var os = require("node:os")
var path = require("node:path")
var load = require("./load.js")

var Sh = load.lib("Sh")
var Paths = load.lib("Paths")

var SH = "/usr/bin/sh"
var TAB = "\t"
var HEADER = "# Netscape HTTP Cookie File\n\n"

// The modes below are only meaningful under the umask the shell runs with.
process.umask(0o022)

var top = fs.mkdtempSync(path.join(os.tmpdir(), "oj-export-"))
var boxes = 0

test.after(function() {
  fs.rmSync(top, { recursive: true, force: true })
})

// ---- The stand-in for yt-dlp ----

// What it does is chosen by the file "mode" next to it: "write" puts the
// file "rows" where --cookies points, "nothing" writes no file, "link"
// plants a link there, "slow" writes and then stays for a moment. Like the
// real tool run without a URL, it ends with status 2.
var FAKE = [
  "#!/usr/bin/node",
  "\"use strict\"",
  "var fs = require(\"fs\")",
  "var path = require(\"path\")",
  "var here = __dirname",
  "var args = process.argv.slice(2)",
  "fs.appendFileSync(path.join(here, \"log\"), JSON.stringify({",
  "  argv: args, env: Object.keys(process.env).sort(), tmpdir: process.env.TMPDIR || null",
  "}) + \"\\n\")",
  "var mode = fs.readFileSync(path.join(here, \"mode\"), \"utf8\").trim()",
  "var target = args[args.indexOf(\"--cookies\") + 1]",
  "var rows = path.join(here, \"rows\")",
  "if (mode === \"link\") fs.symlinkSync(rows, target)",
  "if (mode === \"write\" || mode === \"slow\") fs.writeFileSync(target, fs.readFileSync(rows))",
  "if (mode === \"slow\") {",
  "  fs.writeFileSync(path.join(here, \"started\"), \"\")",
  "  setTimeout(function() { process.exit(2) }, 700)",
  "} else {",
  "  process.exit(2)",
  "}"
].join("\n") + "\n"

// ---- Invented cookies ----

function row(domain, name, value, httpOnly) {
  var fields = [domain, domain.charAt(0) === "." ? "TRUE" : "FALSE", "/", "TRUE", "1893456000", name, value]
  return (httpOnly ? "#HttpOnly_" : "") + fields.join(TAB)
}

var LOGIN = row(".youtube.com", "LOGIN_INFO", "invented-login-info", true)
var SAPISID = row(".youtube.com", "SAPISID", "invented-sapisid", false)
var THIRD_PARTY = row(".youtube.com", "__Secure-3PAPISID", "invented-3papisid", false)
var PREF = row("www.youtube.com", "PREF", "invented-pref", false)
var BARE = row("youtube.com", "SOCS", "invented-socs", false)
var EMPTY_VALUE = row(".youtube.com", "EMPTY", "", false)

// Rows of other sites, and rows that only look like YouTube's.
var FOREIGN = [
  row(".google.com", "SID", "invented-google-sid", false),
  row(".google.com", "LOGIN_INFO", "invented-google-login", true),
  row("accounts.google.com", "__Host-GAPS", "invented-gaps", true),
  row(".example.com", "session", "invented-session", false),
  row(".notyoutube.com", "SAPISID", "invented-lookalike", false),
  row("fakeyoutube.com", "LOGIN_INFO", "invented-lookalike", true),
  row(".youtube.com.example", "LOGIN_INFO", "invented-suffix", true),
  row(".youtube.community", "LOGIN_INFO", "invented-suffix", false),
  row(".YOUTUBE.COM", "LOGIN_INFO", "invented-capitals", false),
  row(".youtube.com ", "LOGIN_INFO", "invented-blank", false),
  row(" .youtube.com", "LOGIN_INFO", "invented-blank", false),
  row("*.youtube.com", "LOGIN_INFO", "invented-pattern", false),
  row("x/.youtube.com", "LOGIN_INFO", "invented-path", false)
]

// Lines that are no cookie row at all.
var MALFORMED = [
  ".youtube.com" + TAB + "TRUE" + TAB + "/" + TAB + "TRUE" + TAB + "1893456000" + TAB + "LOGIN_INFO",
  row(".youtube.com", "LOGIN_INFO", "invented" + TAB + "extra-field", false),
  ".youtube.com LOGIN_INFO invented-spaces",
  "# " + row(".youtube.com", "LOGIN_INFO", "invented-comment", false),
  "#HttpOnly_",
  TAB + TAB + TAB + TAB + TAB + TAB,
  "LOGIN_INFO",
  "$(id)" + TAB + "`id`" + TAB + "/" + TAB + "TRUE" + TAB + "0" + TAB + "LOGIN_INFO" + TAB + "$HOME"
]

function exported(lines) {
  return "# Netscape HTTP Cookie File\n# This file is generated by a test.  Do not edit.\n\n"
    + lines.join("\n") + "\n"
}

// ---- Test directories ----

// A fresh test directory laid out the way the plugin's paths are: a private
// runtime directory with the directory of sign-in attempts, a home, and
// the stand-in tool with its files.
function box(homeName) {
  var root = path.join(top, String(++boxes))
  var runtimeBase = path.join(root, "run")
  var paths = Paths.resolve({
    XDG_RUNTIME_DIR: runtimeBase, XDG_STATE_HOME: null, XDG_DATA_HOME: null,
    HOME: path.join(root, homeName || "home")
  })
  assert.strictEqual(paths.ok, true)
  fs.mkdirSync(paths.signinDir, { recursive: true, mode: 0o700 })
  var tool = path.join(root, "tool")
  fs.mkdirSync(tool)
  fs.writeFileSync(path.join(tool, "yt-dlp"), FAKE, { mode: 0o755 })
  fs.chmodSync(path.join(tool, "yt-dlp"), 0o755)
  var b = {
    root: root, paths: paths, tool: tool, ytdlp: path.join(tool, "yt-dlp"),
    attempt: Paths.signinAttemptDir(paths, 1)
  }
  b.profile = b.attempt + "/profile"
  return b
}

function run(script, zero, args, input) {
  var options = { encoding: "utf8", cwd: top, env: { PATH: "/usr/bin", LANG: "C.UTF-8" } }
  if (typeof input === "string") options.input = input
  var result = childProcess.spawnSync(SH, ["-c", script, zero].concat(args), options)
  return { status: result.status, stdout: result.stdout, stderr: result.stderr }
}

function prepareData(b) {
  var result = run(Sh.PREPARE_DATA, "omajuke-prepare-data", [b.paths.dataDir, b.paths.jarFile])
  result.tokens = result.stdout.split("\n").filter(Boolean)
  return result
}

function signinDirs(b, family, input) {
  return run(Sh.SIGNIN_DIRS, "omajuke-signin-dirs", [b.attempt, family], input)
}

// A test directory in which the browser stage is over: the data directory is
// prepared, the attempt directory exists, and the stand-in will write these
// lines as the profile's cookies.
function ready(lines, homeName) {
  var b = box(homeName)
  assert.deepStrictEqual(prepareData(b).tokens, ["ok"])
  assert.strictEqual(signinDirs(b, "chromium").status, 0)
  fs.writeFileSync(path.join(b.tool, "mode"), "write")
  fs.writeFileSync(path.join(b.tool, "rows"), exported(lines))
  return b
}

function exportArgs(b, name) {
  return [name === undefined ? "chrome" : name, b.profile, b.attempt, b.paths.jarFile, b.ytdlp]
}

function cookieExport(b, name) {
  return run(Sh.COOKIE_EXPORT, "omajuke-export", exportArgs(b, name))
}

function calls(b) {
  var file = path.join(b.tool, "log")
  if (!exists(file)) return []
  var lines = fs.readFileSync(file, "utf8").split("\n").filter(Boolean)
  return lines.map(function(line) { return JSON.parse(line) })
}

function mode(file) {
  return (fs.lstatSync(file).mode & 0o7777).toString(8)
}

function exists(file) {
  try {
    fs.lstatSync(file)
    return true
  } catch (error) {
    return false
  }
}

function names(dir) {
  return fs.readdirSync(dir).sort()
}

// ---- PREPARE_DATA ----

test("prepare-data creates the data directory with mode 700 and reports no login", function() {
  var b = box()
  var result = prepareData(b)
  assert.strictEqual(result.status, 0)
  assert.deepStrictEqual(result.tokens, ["ok"])
  assert.strictEqual(result.stderr, "")
  assert.strictEqual(mode(b.paths.dataDir), "700")
  assert.deepStrictEqual(names(b.paths.dataDir), [])
})

test("prepare-data tightens a data directory that exists with a wider mode", function() {
  var b = box()
  fs.mkdirSync(b.paths.dataDir, { recursive: true })
  fs.chmodSync(b.paths.dataDir, 0o755)
  assert.deepStrictEqual(prepareData(b).tokens, ["ok"])
  assert.strictEqual(mode(b.paths.dataDir), "700")
})

test("prepare-data refuses a data directory that is a link or not a directory", function() {
  var linked = box()
  var elsewhere = path.join(linked.root, "elsewhere")
  fs.mkdirSync(elsewhere)
  fs.chmodSync(elsewhere, 0o755)
  fs.writeFileSync(path.join(elsewhere, "cookies.txt"), "kept\n")
  fs.writeFileSync(path.join(elsewhere, ".cookies.txt.AbC123"), "kept\n")
  fs.mkdirSync(path.dirname(linked.paths.dataDir), { recursive: true })
  fs.symlinkSync(elsewhere, linked.paths.dataDir)
  var refused = prepareData(linked)
  assert.strictEqual(refused.status, 3)
  assert.deepStrictEqual(refused.tokens, ["bad-dir"])
  assert.strictEqual(mode(elsewhere), "755", "the link's target keeps its mode")
  assert.deepStrictEqual(names(elsewhere), [".cookies.txt.AbC123", "cookies.txt"], "and its files")
  assert.strictEqual(mode(path.join(elsewhere, "cookies.txt")), "644")

  var dangling = box()
  fs.mkdirSync(path.dirname(dangling.paths.dataDir), { recursive: true })
  fs.symlinkSync(path.join(dangling.root, "not-there"), dangling.paths.dataDir)
  assert.deepStrictEqual(prepareData(dangling).tokens, ["bad-dir"])
  assert.strictEqual(exists(path.join(dangling.root, "not-there")), false, "nothing is made through a link")

  var file = box()
  fs.mkdirSync(path.dirname(file.paths.dataDir), { recursive: true })
  fs.writeFileSync(file.paths.dataDir, "a file\n")
  var blocked = prepareData(file)
  assert.strictEqual(blocked.status, 3)
  assert.deepStrictEqual(blocked.tokens, ["bad-dir"])
  assert.strictEqual(fs.readFileSync(file.paths.dataDir, "utf8"), "a file\n")
})

test("prepare-data reports a login only if it is a regular file of ours, and makes it private", function() {
  var b = box()
  fs.mkdirSync(b.paths.dataDir, { recursive: true })
  fs.writeFileSync(b.paths.jarFile, HEADER)
  fs.chmodSync(b.paths.jarFile, 0o644)
  assert.deepStrictEqual(prepareData(b).tokens, ["jar", "ok"])
  assert.strictEqual(mode(b.paths.jarFile), "600")
  assert.strictEqual(fs.readFileSync(b.paths.jarFile, "utf8"), HEADER, "it is not read or rewritten")

  var linked = box()
  var target = path.join(linked.root, "someone-elses.txt")
  fs.writeFileSync(target, HEADER)
  fs.chmodSync(target, 0o644)
  fs.mkdirSync(linked.paths.dataDir, { recursive: true })
  fs.symlinkSync(target, linked.paths.jarFile)
  assert.deepStrictEqual(prepareData(linked).tokens, ["ok"], "a link is no login")
  assert.strictEqual(mode(target), "644", "and what it points to is left alone")

  var dir = box()
  fs.mkdirSync(dir.paths.jarFile, { recursive: true })
  assert.deepStrictEqual(prepareData(dir).tokens, ["ok"], "a directory is no login")
})

test("prepare-data deletes only the export's own unfinished files", function() {
  var b = box()
  fs.mkdirSync(b.paths.dataDir, { recursive: true })
  var kept = ["cookies.txt", "cookies.txt.bak", ".cookies.txt.toolong", ".cookies.txt.short", "notes.txt",
    ".cookies.txt", "cookies.txt.AbC123"]
  var deleted = [".cookies.txt.AbC123", ".cookies.txt.000000"]
  kept.concat(deleted).forEach(function(name) { fs.writeFileSync(path.join(b.paths.dataDir, name), "x\n") })
  // A directory with a matching name is not a file of ours, and what is
  // below a subdirectory is not looked at.
  fs.mkdirSync(path.join(b.paths.dataDir, ".cookies.txt.dir123"))
  fs.mkdirSync(path.join(b.paths.dataDir, "sub"))
  fs.writeFileSync(path.join(b.paths.dataDir, "sub", ".cookies.txt.AbC123"), "x\n")
  assert.deepStrictEqual(prepareData(b).tokens, ["jar", "ok"])
  assert.deepStrictEqual(names(b.paths.dataDir), kept.concat([".cookies.txt.dir123", "sub"]).sort())
  assert.deepStrictEqual(names(path.join(b.paths.dataDir, "sub")), [".cookies.txt.AbC123"])
})

test("prepare-data treats hostile directory names as names", function() {
  var homes = ["first last", "o'brien", "a\"b", "$(touch pwned)", "`touch pwned`", "semi;touch pwned", "-rf",
    "star*"]
  homes.forEach(function(home) {
    var b = box(home)
    var result = prepareData(b)
    assert.deepStrictEqual(result.tokens, ["ok"], home)
    assert.strictEqual(result.stderr, "", home)
    assert.strictEqual(mode(b.paths.dataDir), "700", home)
    fs.writeFileSync(b.paths.jarFile, HEADER)
    assert.deepStrictEqual(prepareData(b).tokens, ["jar", "ok"], home)
    assert.strictEqual(exists(path.join(top, "pwned")), false, home)
    assert.strictEqual(exists(path.join(b.root, "pwned")), false, home)
  })
})

// ---- SIGNIN_DIRS ----

test("signin-dirs makes the attempt directory, its profile and its empty configuration, private", function() {
  var b = box()
  var result = signinDirs(b, "chromium")
  assert.strictEqual(result.status, 0)
  assert.strictEqual(result.stdout + result.stderr, "")
  assert.deepStrictEqual(names(b.attempt), ["config", "profile"])
  var made = [b.attempt, b.attempt + "/profile", b.attempt + "/config"]
  made.forEach(function(dir) { assert.strictEqual(mode(dir), "700", dir) })
  assert.deepStrictEqual(names(b.attempt + "/profile"), [])
  assert.deepStrictEqual(names(b.attempt + "/config"), [], "no flag file can be found there")
})

test("signin-dirs writes the preferences file for firefox only, private and exact", function() {
  var text = "user_pref(\"example.pref\", false);\n// a 'quoted' $(line) with a \\ in it\n"
  var firefox = box()
  assert.strictEqual(signinDirs(firefox, "firefox", text).status, 0)
  assert.deepStrictEqual(names(firefox.attempt + "/profile"), ["user.js"])
  assert.strictEqual(fs.readFileSync(firefox.attempt + "/profile/user.js", "utf8"), text)
  assert.strictEqual(mode(firefox.attempt + "/profile/user.js"), "600")

  var others = ["chromium", "", "Firefox", "firefox ", "firefox\n", "-n", "$(id)"]
  others.forEach(function(family) {
    var b = box()
    assert.strictEqual(signinDirs(b, family, text).status, 0, family)
    assert.deepStrictEqual(names(b.attempt + "/profile"), [], family)
  })
})

test("signin-dirs never starts on a directory that is already there", function() {
  var b = box()
  fs.mkdirSync(b.attempt + "/profile", { recursive: true })
  fs.writeFileSync(b.attempt + "/profile/planted", "kept\n")
  var result = signinDirs(b, "firefox", "text\n")
  assert.strictEqual(result.status, 4)
  assert.deepStrictEqual(names(b.attempt), ["profile"], "nothing was added")
  assert.deepStrictEqual(names(b.attempt + "/profile"), ["planted"], "and nothing removed")

  var linked = box()
  var elsewhere = path.join(linked.root, "elsewhere")
  fs.mkdirSync(elsewhere)
  fs.symlinkSync(elsewhere, linked.attempt)
  assert.strictEqual(signinDirs(linked, "firefox", "text\n").status, 4)
  assert.deepStrictEqual(names(elsewhere), [], "nothing is made through a link")

  var orphan = box()
  fs.rmSync(orphan.paths.signinDir, { recursive: true })
  assert.strictEqual(signinDirs(orphan, "chromium").status, 4, "no parent is created on the way")
  assert.strictEqual(exists(orphan.paths.signinDir), false)
})

test("signin-dirs takes its attempt directory literally", function() {
  var odd = ["first last", "o'brien", "$(touch pwned)", "semi;touch pwned", "-p"]
  odd.forEach(function(name) {
    var b = box()
    b.attempt = path.join(b.paths.signinDir, name)
    assert.strictEqual(signinDirs(b, "firefox", "x\n").status, 0, name)
    assert.deepStrictEqual(names(b.paths.signinDir), [name])
    assert.deepStrictEqual(names(b.attempt), ["config", "profile"], name)
    assert.strictEqual(exists(path.join(top, "pwned")), false, name)
  })
})

// ---- COOKIE_EXPORT: what is kept ----

test("the export keeps YouTube's rows and nothing else, in a private file", function() {
  var mine = [SAPISID, LOGIN, PREF, BARE, THIRD_PARTY, EMPTY_VALUE]
  var mixed = [FOREIGN[0], SAPISID, FOREIGN[1], LOGIN, FOREIGN[2], MALFORMED[0], PREF, FOREIGN[3], BARE]
    .concat(FOREIGN.slice(4), [THIRD_PARTY], MALFORMED.slice(1), [EMPTY_VALUE])
  var b = ready(mixed)
  var result = cookieExport(b)
  assert.strictEqual(result.stdout, "ok\n")
  assert.strictEqual(result.stderr, "")
  assert.strictEqual(result.status, 0)
  assert.strictEqual(fs.readFileSync(b.paths.jarFile, "utf8"), HEADER + mine.join("\n") + "\n")
  assert.strictEqual(mode(b.paths.jarFile), "600")
  assert.strictEqual(mode(b.paths.dataDir), "700")
  assert.deepStrictEqual(names(b.paths.dataDir), ["cookies.txt"], "no temporary file is left")
  assert.strictEqual(exists(b.attempt), false, "the profile and the unfiltered export are gone")
  assert.deepStrictEqual(names(b.paths.signinDir), [])
})

test("every row that is kept names youtube.com or a subdomain of it", function() {
  var b = ready(FOREIGN.concat(MALFORMED, [LOGIN, SAPISID]))
  assert.strictEqual(cookieExport(b).stdout, "ok\n")
  var rows = fs.readFileSync(b.paths.jarFile, "utf8").slice(HEADER.length).split("\n").filter(Boolean)
  assert.deepStrictEqual(rows, [LOGIN, SAPISID])
  var text = fs.readFileSync(b.paths.jarFile, "utf8")
  assert.ok(text.indexOf("google") === -1 && text.indexOf("example") === -1)
  assert.ok(text.indexOf("generated by a test") === -1, "the header is our own, not copied")
})

test("a file without a final newline loses no row", function() {
  var b = ready([SAPISID])
  fs.writeFileSync(path.join(b.tool, "rows"), exported([SAPISID]) + LOGIN)
  assert.strictEqual(cookieExport(b).stdout, "ok\n")
  assert.strictEqual(fs.readFileSync(b.paths.jarFile, "utf8"), HEADER + SAPISID + "\n" + LOGIN + "\n")
})

test("a row is copied byte for byte, whatever its value holds", function() {
  var values = ["a b  c", "back\\slash\\n", "$(id) `id` $HOME", "\"double\" 'single'", "-n", "%s%d%%", "*",
    "caf\u00e9 \u65e5\u672c", "=;,:"]
  var lines = [LOGIN, SAPISID].concat(values.map(function(value, i) {
    return row(".youtube.com", "VALUE" + i, value, i % 2 === 0)
  }))
  var b = ready(lines)
  assert.strictEqual(cookieExport(b).stdout, "ok\n")
  assert.strictEqual(fs.readFileSync(b.paths.jarFile, "utf8"), HEADER + lines.join("\n") + "\n")
})

// ---- COOKIE_EXPORT: not signed in ----

test("without a login among YouTube's rows nothing is saved", function() {
  var sets = [
    ["no rows at all", []],
    ["no LOGIN_INFO", [SAPISID, THIRD_PARTY, PREF]],
    ["no signing key", [LOGIN, PREF]],
    ["the login is another site's", [FOREIGN[1], SAPISID, row(".google.com", "SAPISID", "invented", false)]],
    ["the names are only values", [row(".youtube.com", "PREF", "LOGIN_INFO", false),
      row(".youtube.com", "OTHER", "SAPISID", false)]],
    ["the names are only prefixes", [row(".youtube.com", "LOGIN_INFO2", "invented", false),
      row(".youtube.com", "XSAPISID", "invented", false)]],
    ["the login rows are malformed", MALFORMED.concat([SAPISID])]
  ]
  sets.forEach(function(set) {
    var b = ready(set[1])
    var result = cookieExport(b)
    assert.strictEqual(result.stdout, "not-signed-in\n", set[0])
    assert.strictEqual(result.status, 0, set[0])
    assert.deepStrictEqual(names(b.paths.dataDir), [], set[0] + ": no file, finished or not")
    assert.strictEqual(exists(b.attempt), false, set[0])
  })
})

test("either signing key is enough", function() {
  var first = ready([LOGIN, SAPISID])
  assert.strictEqual(cookieExport(first).stdout, "ok\n")
  var second = ready([LOGIN, THIRD_PARTY])
  assert.strictEqual(cookieExport(second).stdout, "ok\n")
})

test("a failed attempt leaves an earlier login as it was", function() {
  var b = ready([SAPISID])
  fs.writeFileSync(b.paths.jarFile, "earlier\n")
  assert.strictEqual(cookieExport(b).stdout, "not-signed-in\n")
  assert.strictEqual(fs.readFileSync(b.paths.jarFile, "utf8"), "earlier\n")
  assert.deepStrictEqual(names(b.paths.dataDir), ["cookies.txt"])
})

// ---- COOKIE_EXPORT: how the file comes to be ----

test("the login is created private by mktemp and renamed into place, not made private later", function() {
  var text = Sh.COOKIE_EXPORT
  assert.ok(text.indexOf("umask 077\n") === 0)
  assert.ok(text.indexOf("chmod") === -1, "no mode is repaired after the fact")
  var made = text.indexOf("t=$(/usr/bin/mktemp -- \"$d/.cookies.txt.XXXXXX\")")
  var filled = text.indexOf("} > \"$t\"")
  var moved = text.indexOf("/usr/bin/mv -fT -- \"$t\" \"$4\"")
  assert.ok(made !== -1 && made < filled && filled < moved)
  // The login file itself is only ever the target of the rename.
  assert.strictEqual(text.split("\"$4\"").length - 1, 1)
  assert.ok(text.indexOf("> \"$4\"") === -1)
})

test("an existing login is replaced in one step, and a link planted there is not followed", function() {
  var b = ready([LOGIN, SAPISID])
  fs.writeFileSync(b.paths.jarFile, "earlier\n")
  fs.chmodSync(b.paths.jarFile, 0o644)
  assert.strictEqual(cookieExport(b).stdout, "ok\n")
  assert.strictEqual(fs.readFileSync(b.paths.jarFile, "utf8"), HEADER + LOGIN + "\n" + SAPISID + "\n")
  assert.strictEqual(mode(b.paths.jarFile), "600")

  var linked = ready([LOGIN, SAPISID])
  var target = path.join(linked.root, "target.txt")
  fs.writeFileSync(target, "untouched\n")
  fs.symlinkSync(target, linked.paths.jarFile)
  assert.strictEqual(cookieExport(linked).stdout, "ok\n")
  assert.strictEqual(fs.readFileSync(target, "utf8"), "untouched\n")
  assert.strictEqual(fs.lstatSync(linked.paths.jarFile).isFile(), true, "the link was replaced by the file")
  assert.strictEqual(mode(linked.paths.jarFile), "600")

  var dir = ready([LOGIN, SAPISID])
  fs.mkdirSync(dir.paths.jarFile)
  var blocked = cookieExport(dir)
  assert.strictEqual(blocked.stdout, "error\n")
  assert.strictEqual(blocked.status, 1)
  assert.deepStrictEqual(names(dir.paths.dataDir), ["cookies.txt"], "the temporary file is gone again")
  assert.deepStrictEqual(names(dir.paths.jarFile), [], "and nothing was put inside the directory")
  assert.strictEqual(exists(dir.attempt), false)
})

test("a data directory that is a link or missing is refused before anything is read", function() {
  var linked = ready([LOGIN, SAPISID])
  var elsewhere = path.join(linked.root, "elsewhere")
  fs.mkdirSync(elsewhere)
  fs.rmSync(linked.paths.dataDir, { recursive: true })
  fs.symlinkSync(elsewhere, linked.paths.dataDir)
  var refused = cookieExport(linked)
  assert.strictEqual(refused.stdout, "error\n")
  assert.strictEqual(refused.status, 1)
  assert.deepStrictEqual(names(elsewhere), [], "nothing is written through the link")
  assert.deepStrictEqual(calls(linked), [], "the profile was not read")
  assert.strictEqual(exists(linked.attempt), false)

  var missing = ready([LOGIN, SAPISID])
  fs.rmSync(missing.paths.dataDir, { recursive: true })
  assert.strictEqual(cookieExport(missing).stdout, "error\n")
  assert.strictEqual(exists(missing.paths.dataDir), false, "the export creates no directory")
  assert.deepStrictEqual(calls(missing), [])
  assert.strictEqual(exists(missing.attempt), false)
})

// ---- COOKIE_EXPORT: what is read, and how the tool is run ----

test("yt-dlp is run once, offline, on the attempt's own profile and with nothing from the user", function() {
  var browsers = ["chrome", "chromium", "brave", "vivaldi", "firefox"]
  assert.deepStrictEqual(Sh.COOKIE_BROWSERS.slice(), browsers)
  browsers.forEach(function(name) {
    var b = ready([LOGIN, SAPISID])
    assert.strictEqual(cookieExport(b, name).stdout, "ok\n", name)
    var seen = calls(b)
    assert.strictEqual(seen.length, 1, name)
    assert.deepStrictEqual(seen[0].argv, [
      "--ignore-config", "--no-plugin-dirs", "--no-cache-dir", "--no-remote-components",
      "--cookies-from-browser", name + "+basictext:" + b.attempt + "/profile",
      "--cookies", b.attempt + "/export.txt"
    ], name)
    assert.strictEqual(seen[0].tmpdir, b.attempt, name + ": temporary copies stay in the attempt directory")
    assert.ok(seen[0].argv.every(function(arg) { return !/^https?:/.test(arg) }), "no address is given")
    assert.ok(seen[0].argv.join(" ").indexOf("invented") === -1, "no cookie value is in the command line")
    assert.ok(seen[0].env.indexOf("TMPDIR") !== -1)
  })
})

test("only a bare browser name is accepted: no other profile, keyring or container can be named", function() {
  var hostile = [
    "", "Chrome", "chrome ", " chrome", "chrome\n", "chrome:/home/user/.config/google-chrome",
    "chrome+gnomekeyring", "chrome+basictext:/home/user/.config/chromium::x", "firefox::container",
    "firefox:default-release", "edge", "opera", "safari", "whale", "chrome|firefox", "*", "chrom?",
    "$(id)", "-", "--exec"
  ]
  hostile.forEach(function(name) {
    var b = ready([LOGIN, SAPISID])
    var result = cookieExport(b, name)
    assert.strictEqual(result.stdout, "error\n", JSON.stringify(name))
    assert.strictEqual(result.status, 1, JSON.stringify(name))
    assert.deepStrictEqual(calls(b), [], JSON.stringify(name) + ": nothing was run")
    assert.deepStrictEqual(names(b.paths.dataDir), [], JSON.stringify(name))
    assert.strictEqual(exists(b.attempt), false, JSON.stringify(name))
  })
})

test("only the profile inside the attempt directory is accepted", function() {
  var b = ready([LOGIN, SAPISID])
  var everyday = path.join(b.root, "home", ".config", "chromium")
  fs.mkdirSync(everyday, { recursive: true })
  var others = [
    everyday, b.attempt, b.attempt + "/config", b.attempt + "/profile/", b.attempt + "/profile/..",
    b.attempt + "/../1/profile", "", "profile"
  ]
  others.forEach(function(profile) {
    var again = ready([LOGIN, SAPISID])
    var args = [
      "chrome", profile.replace(b.attempt, again.attempt), again.attempt, again.paths.jarFile, again.ytdlp
    ]
    var result = run(Sh.COOKIE_EXPORT, "omajuke-export", args)
    assert.strictEqual(result.stdout, "error\n", profile)
    assert.deepStrictEqual(calls(again), [], profile + ": nothing was run")
    assert.deepStrictEqual(names(again.paths.dataDir), [], profile)
  })
  assert.deepStrictEqual(names(everyday), [], "the everyday profile was never touched")

  // A profile that is a link to somewhere else is not read either.
  var linked = ready([LOGIN, SAPISID])
  fs.rmSync(linked.profile, { recursive: true })
  fs.symlinkSync(everyday, linked.profile)
  assert.strictEqual(cookieExport(linked).stdout, "error\n")
  assert.deepStrictEqual(calls(linked), [])
  assert.strictEqual(exists(everyday), true, "removing the attempt removes the link, not its target")
})

test("no export file, or one that is a link, is an error and saves nothing", function() {
  var none = ready([LOGIN, SAPISID])
  fs.writeFileSync(path.join(none.tool, "mode"), "nothing")
  var result = cookieExport(none)
  assert.strictEqual(result.stdout, "error\n")
  assert.strictEqual(result.status, 1)
  assert.deepStrictEqual(names(none.paths.dataDir), [])
  assert.strictEqual(exists(none.attempt), false)

  var linked = ready([LOGIN, SAPISID])
  fs.writeFileSync(path.join(linked.tool, "mode"), "link")
  assert.strictEqual(cookieExport(linked).stdout, "error\n")
  assert.deepStrictEqual(names(linked.paths.dataDir), [])
  assert.strictEqual(exists(path.join(linked.tool, "rows")), true, "what the link pointed to is still there")

  var absent = ready([LOGIN, SAPISID])
  absent.ytdlp = path.join(absent.root, "not-installed")
  assert.strictEqual(cookieExport(absent).stdout, "error\n")
  assert.strictEqual(exists(absent.attempt), false)
})

test("the export prints one word and never a cookie", function() {
  var sets = [[LOGIN, SAPISID], [SAPISID], FOREIGN, MALFORMED]
  sets.forEach(function(lines) {
    var b = ready(lines)
    var result = cookieExport(b)
    assert.match(result.stdout, /^(ok|not-signed-in|error)\n$/)
    assert.strictEqual(result.stderr, "")
    assert.ok((result.stdout + result.stderr).indexOf("invented") === -1)
  })
})

test("a data directory with spaces, quotes or shell characters is taken literally", function() {
  var homes = [
    "first last", "o'brien", "a\"b", "$(touch pwned)", "`touch pwned`", "semi;touch pwned", "star*"
  ]
  homes.forEach(function(home) {
    var b = ready([LOGIN, SAPISID], home)
    var result = cookieExport(b)
    assert.strictEqual(result.stdout, "ok\n", home)
    assert.strictEqual(result.stderr, "", home)
    assert.deepStrictEqual(names(b.paths.dataDir), ["cookies.txt"], home)
    assert.strictEqual(mode(b.paths.jarFile), "600", home)
    assert.strictEqual(exists(path.join(top, "pwned")), false, home)
    assert.strictEqual(exists(path.join(b.root, "pwned")), false, home)
  })
})

// ---- COOKIE_EXPORT: ended from outside ----

test("ended with SIGTERM, the export removes the attempt directory and saves nothing", async function() {
  var b = ready([LOGIN, SAPISID])
  fs.writeFileSync(path.join(b.tool, "mode"), "slow")
  var argv = ["-c", Sh.COOKIE_EXPORT, "omajuke-export"].concat(exportArgs(b))
  var child = childProcess.spawn(SH, argv, { cwd: top, env: { PATH: "/usr/bin", LANG: "C.UTF-8" } })
  var out = ""
  child.stdout.on("data", function(chunk) { out += chunk })
  var ended = new Promise(function(resolve) {
    child.on("close", function(code, signal) { resolve({ code: code, signal: signal }) })
  })
  // The stand-in has written the unfiltered export and is still running.
  var started = path.join(b.tool, "started")
  for (var i = 0; i < 200 && !exists(started); i++) {
    await new Promise(function(resolve) { setTimeout(resolve, 25) })
  }
  assert.strictEqual(exists(started), true)
  assert.strictEqual(exists(b.attempt + "/export.txt"), true)
  child.kill("SIGTERM")
  var result = await ended
  assert.strictEqual(result.code, 1)
  assert.strictEqual(out, "", "nothing is reported for an export that was ended")
  assert.strictEqual(exists(b.attempt), false, "the profile and the unfiltered export are gone")
  assert.deepStrictEqual(names(b.paths.dataDir), [], "and no login was saved, finished or not")
})

test("the attempt directory goes on every exit the export makes itself", function() {
  var text = Sh.COOKIE_EXPORT
  var lines = text.split("\n")
  assert.strictEqual(lines[0], "umask 077")
  // The traps are set before anything can fail or be read.
  assert.match(lines[2], /^trap '\/usr\/bin\/rm -rf -- "\$3"; .*' EXIT$/)
  assert.strictEqual(lines[3], "trap 'exit 1' HUP INT TERM")
  assert.ok(text.indexOf("\"$5\"") > text.indexOf("trap 'exit 1' HUP INT TERM"))
  // Nothing replaces or clears them later.
  assert.strictEqual(text.split("trap ").length - 1, 2)
})
