.pragma library

// Input and expectation table for lib/Ids.js: which texts are video links
// (and which id they name), which are valid ids, what the URL builders
// return and refuse, and which texts look like a link, an address or a path
// and are therefore never searched for. The same table runs under node and
// inside Qt's JavaScript engine, so both must agree on every row.

var MODULE = "Ids"
var CASES = [
  // ---- parseVideoRef: links that name a video ----
  { fn: "parseVideoRef", args: ["https://youtu.be/Abc123Def4Q", false], expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=Abc123Def4Q", false],
    expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=Abc123Def4Q&list=PL0123456789&t=42s", false],
    expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?feature=share&v=Abc123Def4Q", false],
    expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=Abc123Def4Q#t=10", false],
    expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["https://youtu.be/Abc123Def4Q?si=AbCdEfGh", false], expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["https://music.youtube.com/watch?v=Abc123Def4Q", false],
    expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["https://m.youtube.com/watch?v=Abc123Def4Q", false], expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/shorts/Abc123Def4Q", false], expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/live/Abc123Def4Q?feature=share", false],
    expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/embed/Abc123Def4Q", false], expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["youtube.com/watch?v=Abc123Def4Q", false], expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["http://www.youtube.com/watch?v=Abc123Def4Q", false], expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["  https://youtu.be/Abc123Def4Q\n", false], expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["\ufeffhttps://youtu.be/Abc123Def4Q\u00a0", false], expect: "Abc123Def4Q" },
  // Only whitespace is trimmed: a next-line control, a Mongolian vowel
  // separator or a zero-width space in front is part of the text.
  { fn: "parseVideoRef", args: ["\u0085https://youtu.be/Abc123Def4Q", false], expect: "" },
  { fn: "parseVideoRef", args: ["\u180ehttps://youtu.be/Abc123Def4Q", false], expect: "" },
  { fn: "parseVideoRef", args: ["\u200bhttps://youtu.be/Abc123Def4Q", false], expect: "" },
  // Ids that look like an option or a prototype member are ordinary ids.
  { fn: "parseVideoRef", args: ["https://youtu.be/--no-config", false], expect: "--no-config" },
  { fn: "parseVideoRef", args: ["https://youtu.be/constructor", false], expect: "constructor" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=-AAAAAAAAAA", false],
    expect: "-AAAAAAAAAA" },
  // Two v parameters still give exactly one valid id.
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAAA&v=BBBBBBBBBBB", false],
    expect: "BBBBBBBBBBB" },

  // ---- parseVideoRef: a bare id counts only where the caller allows it ----
  { fn: "parseVideoRef", args: ["Abc123Def4Q", true], expect: "Abc123Def4Q" },
  { fn: "parseVideoRef", args: ["Abc123Def4Q", false], expect: "" },
  { fn: "parseVideoRef", args: ["constructor", false], expect: "" },
  { fn: "parseVideoRef", args: ["constructor", true], expect: "constructor" },
  { fn: "parseVideoRef", args: ["--no-config", false], expect: "" },
  { fn: "parseVideoRef", args: ["--no-config", true], expect: "--no-config" },
  { fn: "parseVideoRef", args: ["documentary", false], expect: "" },
  { fn: "parseVideoRef", args: ["-AAAAAAAAAA\n", true], expect: "-AAAAAAAAAA" },
  { fn: "parseVideoRef", args: ["Abc123Def4Q", 1], expect: "" },
  { fn: "parseVideoRef", args: ["Abc123Def4Q", "true"], expect: "" },
  { fn: "parseVideoRef", args: ["Abc123Def4", true], expect: "" },
  { fn: "parseVideoRef", args: ["Abc123Def4QQ", true], expect: "" },
  { fn: "parseVideoRef", args: ["Abc123Def4!", true], expect: "" },
  { fn: "parseVideoRef", args: ["dQw4w9 gXcQ", true], expect: "" },
  { fn: "parseVideoRef", args: ["-AAAAAAAAAA\nsecond line", true], expect: "" },
  { fn: "parseVideoRef", args: ["-AAAAAAAAAA\n--exec", true], expect: "" },
  { fn: "parseVideoRef", args: ["Abc123Def4Q\u0000", true], expect: "" },

  // ---- parseVideoRef: everything else is refused ----
  { fn: "parseVideoRef", args: ["https://youtube.com@evil.tld/watch?v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com.evil.tld/watch?v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://evil.tld/?u=https://www.youtube.com/watch?v=AAAAAAAAAAA", true],
    expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/redirect?q=https://evil.tld", true], expect: "" },
  { fn: "parseVideoRef",
    args: ["https://www.youtube.com/attribution_link?u=%2Fwatch%3Fv%3DAAAAAAAAAAA", true],
    expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?xv=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch#&v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?a=1#&v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com\\@evil.tld/watch?v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAAA\\", true], expect: "" },
  { fn: "parseVideoRef", args: ["file:///etc/passwd", true], expect: "" },
  { fn: "parseVideoRef", args: ["ytdl://x", true], expect: "" },
  { fn: "parseVideoRef", args: ["av://v4l2:/dev/video0", true], expect: "" },
  { fn: "parseVideoRef", args: ["javascript:alert(1)", true], expect: "" },
  { fn: "parseVideoRef", args: ["ftp://www.youtube.com/watch?v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["//www.youtube.com/watch?v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://xn--youtube-abc.com/watch?v=AAAAAAAAAAA", true], expect: "" },
  // The first letter of the host is the Cyrillic look-alike of "y".
  { fn: "parseVideoRef", args: ["https://www.\u0443outube.com/watch?v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://notyoutube.com/watch?v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://evilyoutu.be/AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com:443/watch?v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com./watch?v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["HTTPS://WWW.YOUTUBE.COM/watch?v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://youtu.be/AAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://youtu.be/AAAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://youtu.be/", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?list=PL0123456789", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/playlist?list=PL0123456789", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/@somechannel", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAA AAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAAA\nhttps://evil.tld/", true],
    expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAAA\u0000", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAAA\u007f", true], expect: "" },
  // A control character, space or backslash anywhere, also behind a complete link.
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAAA&t=1\nsecond line", true],
    expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAAA&t=1 2", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAAA&x=\u0000", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAAA&x=\u007f", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?v=AAAAAAAAAAA&x=\u001b[m", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://www.youtube.com/watch?a=\t&v=AAAAAAAAAAA", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://youtu.be/AAAAAAAAAAA?x=\\", true], expect: "" },
  { fn: "parseVideoRef", args: ["https://youtu.be/AAAAAAAAAAA?x=\r\n--exec", true], expect: "" },
  { fn: "parseVideoRef", args: ["", true], expect: "" },
  { fn: "parseVideoRef", args: ["   ", true], expect: "" },
  { fn: "parseVideoRef", args: [null, true], expect: "" },
  { fn: "parseVideoRef", args: [12345678901, true], expect: "" },
  { fn: "parseVideoRef", args: [["Abc123Def4Q"], true], expect: "" },
  { fn: "parseVideoRef", args: [{ id: "Abc123Def4Q" }, true], expect: "" },
  { fn: "parseVideoRef", args: [{ gen: "repeat", unit: "a", count: 300000 }, true], expect: "" },
  { fn: "parseVideoRef", args: [{ gen: "codes", codes: [55357] }, true], expect: "" },

  // ---- isId ----
  { fn: "isId", args: ["Abc123Def4Q"], expect: true },
  { fn: "isId", args: ["constructor"], expect: true },
  { fn: "isId", args: ["--no-config"], expect: true },
  { fn: "isId", args: ["__proto__"], expect: false },
  { fn: "isId", args: ["Abc123Def4"], expect: false },
  { fn: "isId", args: ["Abc123Def4QQ"], expect: false },
  { fn: "isId", args: ["Abc123Def4Q\n"], expect: false },
  { fn: "isId", args: ["Abc123Def4\u00e9"], expect: false },
  { fn: "isId", args: [""], expect: false },
  { fn: "isId", args: [null], expect: false },
  { fn: "isId", args: [12345678901], expect: false },
  { fn: "isId", args: [["Abc123Def4Q"]], expect: false },

  // ---- watchUrl, thumbUrl, mixUrl: built from a valid id or not at all ----
  { fn: "watchUrl", args: ["Abc123Def4Q"], expect: "https://www.youtube.com/watch?v=Abc123Def4Q" },
  { fn: "watchUrl", args: ["--no-config"], expect: "https://www.youtube.com/watch?v=--no-config" },
  { fn: "watchUrl", args: ["constructor"], expect: "https://www.youtube.com/watch?v=constructor" },
  { fn: "watchUrl", args: ["Abc123Def4"], expect: { throws: true } },
  { fn: "watchUrl", args: ["Abc123Def4Q&list=x"], expect: { throws: true } },
  { fn: "watchUrl", args: ["Abc123Def4Q\n"], expect: { throws: true } },
  { fn: "watchUrl", args: [""], expect: { throws: true } },
  { fn: "watchUrl", args: [null], expect: { throws: true } },
  { fn: "watchUrl", args: [["Abc123Def4Q"]], expect: { throws: true } },
  { fn: "thumbUrl", args: ["Abc123Def4Q"], expect: "https://i.ytimg.com/vi/Abc123Def4Q/mqdefault.jpg" },
  { fn: "thumbUrl", args: ["../../../etc"], expect: { throws: true } },
  { fn: "thumbUrl", args: ["Abc123Def4/"], expect: { throws: true } },
  { fn: "thumbUrl", args: ["Abc123Def4?"], expect: { throws: true } },
  { fn: "thumbUrl", args: [null], expect: { throws: true } },
  { fn: "mixUrl", args: ["Abc123Def4Q"],
    expect: "https://www.youtube.com/watch?v=Abc123Def4Q&list=RDAbc123Def4Q" },
  { fn: "mixUrl", args: ["Abc123Def4&"], expect: { throws: true } },
  { fn: "mixUrl", args: [null], expect: { throws: true } },

  // ---- looksLikeUrl: links, addresses and paths ----
  { fn: "looksLikeUrl", args: ["youtube.com/playlist?list=PL0123456789"], expect: true },
  { fn: "looksLikeUrl", args: ["intranet.example/x?token=abc"], expect: true },
  { fn: "looksLikeUrl", args: ["file:///etc/hostname"], expect: true },
  { fn: "looksLikeUrl", args: ["mailto:a@b.example"], expect: true },
  { fn: "looksLikeUrl", args: ["will.i.am"], expect: true },
  { fn: "looksLikeUrl", args: ["192.168.1.10/admin?token=abc"], expect: true },
  { fn: "looksLikeUrl", args: ["10.0.0.5:8080/stream?key=secret"], expect: true },
  { fn: "looksLikeUrl", args: ["localhost/x?token=abc"], expect: true },
  { fn: "looksLikeUrl", args: ["nas/share/private.mp4"], expect: true },
  { fn: "looksLikeUrl", args: ["//fileserver.corp/x?sig=abc"], expect: true },
  { fn: "looksLikeUrl", args: ["user@git.corp.example/repo?token=abc"], expect: true },
  { fn: "looksLikeUrl", args: ["[fe80::1]/x"], expect: true },
  { fn: "looksLikeUrl", args: ["/home/user/private/file.mp4"], expect: true },
  { fn: "looksLikeUrl", args: ["~/Documents/tax-2025.pdf"], expect: true },
  { fn: "looksLikeUrl", args: ["/home/user/My Documents/tax 2025.pdf"], expect: true },
  { fn: "looksLikeUrl", args: ["https://intranet.example/a b?token=x"], expect: true },
  { fn: "looksLikeUrl", args: ["someone@example.com"], expect: true },
  { fn: "looksLikeUrl", args: ["nas/private.mp4"], expect: true },
  { fn: "looksLikeUrl", args: ["re:zero"], expect: true },
  { fn: "looksLikeUrl", args: ["R&B/Soul"], expect: true },
  { fn: "looksLikeUrl", args: ["/shrug"], expect: true },
  { fn: "looksLikeUrl", args: ["http://example.com"], expect: true },
  { fn: "looksLikeUrl", args: ["HTTPS://EXAMPLE.COM/x"], expect: true },
  { fn: "looksLikeUrl", args: ["smb://nas/share"], expect: true },
  { fn: "looksLikeUrl", args: ["example.com"], expect: true },
  { fn: "looksLikeUrl", args: ["sub.example.co.uk/path"], expect: true },
  { fn: "looksLikeUrl", args: ["127.0.0.1"], expect: true },
  { fn: "looksLikeUrl", args: ["127.0.0.1:8080"], expect: true },
  { fn: "looksLikeUrl", args: ["localhost"], expect: true },
  { fn: "looksLikeUrl", args: ["LOCALHOST:3000"], expect: true },
  { fn: "looksLikeUrl", args: ["[::1]"], expect: true },
  { fn: "looksLikeUrl", args: ["./notes.txt"], expect: true },
  { fn: "looksLikeUrl", args: ["../notes.txt"], expect: true },
  { fn: "looksLikeUrl", args: ["magnet:?xt=urn:btih:abc"], expect: true },
  { fn: "looksLikeUrl", args: ["C:/Users/x/file.mp4"], expect: true },
  { fn: "looksLikeUrl", args: ["x?y=1/z"], expect: true },
  // Judged without the whitespace around it, and in the form it would be
  // sent in: an invisible character in front must not hide an address.
  { fn: "looksLikeUrl", args: ["  https://intranet.example/x  "], expect: true },
  { fn: "looksLikeUrl", args: ["\n192.168.1.10/admin\n"], expect: true },
  { fn: "looksLikeUrl", args: ["\u200bintranet.example"], expect: true },
  { fn: "looksLikeUrl", args: ["\u200b10.0.0.5:8080"], expect: true },
  { fn: "looksLikeUrl", args: ["\u202elocalhost:3000"], expect: true },
  { fn: "looksLikeUrl", args: ["\u0000intranet.example"], expect: true },
  { fn: "looksLikeUrl", args: ["intranet.example #"], expect: true },
  { fn: "looksLikeUrl", args: ["\u0085intranet.example"], expect: true },
  { fn: "looksLikeUrl", args: ["a\u180eb@example.com"], expect: true },
  // An unbroken run longer than any link is a paste, whatever it holds.
  { fn: "looksLikeUrl", args: [{ gen: "repeat", unit: "a", count: 300000 }], expect: true },
  { fn: "looksLikeUrl", args: [{ gen: "repeat", unit: "?", count: 300000 }], expect: true },
  { fn: "looksLikeUrl", args: [{ gen: "repeat", unit: "/", count: 300000 }], expect: true },

  // ---- looksLikeUrl: ordinary queries ----
  { fn: "looksLikeUrl", args: ["AC/DC"], expect: false },
  { fn: "looksLikeUrl", args: ["AC/DC live"], expect: false },
  { fn: "looksLikeUrl", args: ["50/50"], expect: false },
  { fn: "looksLikeUrl", args: ["what is 3:10 to yuma"], expect: false },
  { fn: "looksLikeUrl", args: ["re: zero"], expect: false },
  { fn: "looksLikeUrl", args: ["node js"], expect: false },
  { fn: "looksLikeUrl", args: ["vol.2"], expect: false },
  { fn: "looksLikeUrl", args: ["@mkbhd"], expect: false },
  { fn: "looksLikeUrl", args: ["a=b"], expect: false },
  { fn: "looksLikeUrl", args: ["never gonna give you up"], expect: false },
  { fn: "looksLikeUrl", args: ["documentary"], expect: false },
  { fn: "looksLikeUrl", args: ["Abc123Def4Q"], expect: false },
  { fn: "looksLikeUrl", args: ["C++"], expect: false },
  { fn: "looksLikeUrl", args: ["C#"], expect: false },
  { fn: "looksLikeUrl", args: ["#shorts"], expect: false },
  { fn: "looksLikeUrl", args: ["100%"], expect: false },
  { fn: "looksLikeUrl", args: ["rock & roll"], expect: false },
  { fn: "looksLikeUrl", args: ["what?"], expect: false },
  { fn: "looksLikeUrl", args: ["3.14"], expect: false },
  { fn: "looksLikeUrl", args: ["mr. robot"], expect: false },
  { fn: "looksLikeUrl", args: ["the address intranet.example is down"], expect: false },
  { fn: "looksLikeUrl", args: ["\u200bdocumentary"], expect: false },
  { fn: "looksLikeUrl", args: [""], expect: false },
  { fn: "looksLikeUrl", args: ["   "], expect: false },
  { fn: "looksLikeUrl", args: [{ gen: "repeat", unit: "la ", count: 100000 }], expect: false },
  { fn: "looksLikeUrl", args: [{ gen: "codes", codes: [55357] }], expect: false },
  { fn: "looksLikeUrl", args: [null], expect: false },
  { fn: "looksLikeUrl", args: [42], expect: false },
  { fn: "looksLikeUrl", args: [["example.com"]], expect: false }
]

if (typeof module !== "undefined") {
  module.exports = { MODULE: MODULE, CASES: CASES }
}
